<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Description>A convenient utility for managing Cloudflare R2 buckets, objects, and configuration.</Description>
        <Version Condition="'$(BUILD_VERSION)' == ''">4.0.0</Version>
        <Version Condition="'$(BUILD_VERSION)' != ''">$(BUILD_VERSION)</Version>
        <AssemblyName>Soenneker.Cloudflare.R2</AssemblyName>
        <PackageId>Soenneker.Cloudflare.R2</PackageId>
        <PackageTags>cloudflare r2 storage buckets objects s3 cloudflarer2util util csharp dotnet c# .net</PackageTags>
        <Copyright>Copyright © 2026 Jake Soenneker</Copyright>
        <Authors>Jake Soenneker</Authors>
        <Company>https://soenneker.com</Company>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/soenneker/soenneker.cloudflare.r2</PackageProjectUrl>
        <RepositoryUrl>https://github.com/soenneker/soenneker.cloudflare.r2</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <LangVersion>latest</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Soenneker.Aws.Signing.V4" Version="4.0.5" />
        <PackageReference Include="Soenneker.Cloudflare.Utils.Client" Version="4.0.1012" />
        <PackageReference Include="Soenneker.Utils.Json" Version="4.0.2675" />
    </ItemGroup>
</Project>
